/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package challengealuraconversos;
/**
 *
 * @author juanp
 */
public class Vista_Conversor extends javax.swing.JFrame {

    /**
     * Creates new form Vista_Conversor
     */
    public Vista_Conversor() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Listbox = new javax.swing.JComboBox<>();
        Moneda1 = new javax.swing.JTextField();
        moneda2 = new javax.swing.JTextField();
        Convertir = new javax.swing.JButton();
        Nuevo = new javax.swing.JButton();
        MonSalida = new javax.swing.JLabel();
        MonEntr = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Listbox.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Listbox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "COP a USD", "COP a EUR", "COP a GBP", "COP a JPY", "COP a KRW", "USD a COP", "EUR a COP", "GBP a COP", "JPY a COP", "KRW a COP" }));
        Listbox.setBorder(null);
        jPanel1.add(Listbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 130, 600, 30));
        Listbox.getAccessibleContext().setAccessibleName("");

        Moneda1.setBackground(new java.awt.Color(255, 255, 255));
        Moneda1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Moneda1.setForeground(new java.awt.Color(0, 0, 0));
        Moneda1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Moneda1.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jPanel1.add(Moneda1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 240, 190, 40));

        moneda2.setEditable(false);
        moneda2.setBackground(new java.awt.Color(255, 255, 255));
        moneda2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        moneda2.setForeground(new java.awt.Color(0, 0, 0));
        moneda2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(moneda2, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 240, 190, 40));

        Convertir.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Convertir.setText("Convertir");
        Convertir.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Convertir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConvertirActionPerformed(evt);
            }
        });
        jPanel1.add(Convertir, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 360, 100, -1));

        Nuevo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Nuevo.setText("Nuevo");
        Nuevo.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Nuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NuevoActionPerformed(evt);
            }
        });
        jPanel1.add(Nuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 360, 100, -1));

        MonSalida.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        MonSalida.setForeground(new java.awt.Color(0, 0, 0));
        MonSalida.setText("Moneda2");
        jPanel1.add(MonSalida, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 210, -1, -1));

        MonEntr.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        MonEntr.setForeground(new java.awt.Color(0, 0, 0));
        MonEntr.setText("Moneda1");
        jPanel1.add(MonEntr, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 210, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/VistaSources/icons8-exchange-30.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 250, 30, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Conversor de moneda");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 30, 410, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/VistaSources/Digital Technology Blue Background Banner Beam Lines.jpg"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 0, 100, 110));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/VistaSources/Digital Technology Blue Background Banner Beam Lines.jpg"))); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 110));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 397, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Tasa(int x){
    String[] tasadecambio = {"0.00021", "0.00019", "0.00017", "0.027", "0.27", "4773" ,"5193" ,"5864", "36.47", "3.69"};
   
    canvio(Float.parseFloat(Moneda1.getText()), Float.parseFloat(tasadecambio[x]));
    }
    
    private void canvio(float mon, float camb){
        Float f = mon * camb;
        moneda2.setText(Float.toString(f));
    }
    
    private void ConvertirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConvertirActionPerformed
        
        int x = Listbox.getSelectedIndex();
        Tasa(x);
        
    }//GEN-LAST:event_ConvertirActionPerformed

    private void NuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NuevoActionPerformed
        Moneda1.setText("");
        moneda2.setText("");
        Listbox.setSelectedIndex(0);
    }//GEN-LAST:event_NuevoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Vista_Conversor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Vista_Conversor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Vista_Conversor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Vista_Conversor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Vista_Conversor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton Convertir;
    private javax.swing.JComboBox<String> Listbox;
    private javax.swing.JLabel MonEntr;
    private javax.swing.JLabel MonSalida;
    private javax.swing.JTextField Moneda1;
    public javax.swing.JButton Nuevo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField moneda2;
    // End of variables declaration//GEN-END:variables
}
